server:
  port: 8080

spring:
  profiles:
      active: local
  output:
    ansi:
      enabled: always

  config:
    import: optional:classpath:security-config.yml

  application:
    name: tuto-list
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

file:
  upload-dir: "/Users/seongjun/dev/uploads"