version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: tutolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutolist
      MYSQL_USER: tutolist
      MYSQL_PASSWORD: tutolist
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tutolist-network
  redis:
    image: redis:7.4.2
    container_name: tutolist-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
    driver: local

networks:
  tutolist-network:
    driver: bridge