server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit

spring:
  application:
    name: TutoList
  jpa:
    hibernate:
      ddl-auto: create-drop #create, create-drop, update ...
    properties:
      hibernate:
        show_sql: true
        database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tutoring?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:

auth:
  login:
    username: username
    password: password
    url: /login
    remember-me:
      name: remember-me
      key: test

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
#      springframework: DEBUG